### ISSUE TITLE
simpler boot version of the bot

### ISSUE THREAD

**Issue by dcsan** [mistval/kotoba#103]
optional 'lite' version of the bot which doesn't have so many dependencies to build?

currently we can just remove 
- canvas
- render-furigana

but it does give quite a few errors at startup.
possibly these features could be in a separate service, and then bootup with `LITE=true` to disable looking for them?

```
yarn why canvas
yarn why v1.17.3
[1/4] 🤔  Why do we have the module "canvas"...?
[2/4] 🚚  Initialising dependency graph...
warning kitsu@7.0.0: Node 12 support fixed in 7.0.2
warning eslint > file-entry-cache > flat-cache > circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "canvas@1.6.13"
info Reasons this module exists
   - "render-furigana" depends on it
```

**Comment by mistval** [comment]
🤔 maybe, but if it's the errors that bother you, you can delete the relevant command files from bot/src/discord_commands and bot/src/discord_message_processors. I do plan to move furigana to the worker service some day since that's kinda slow, maybe quiz question rendering too, although that's actually pretty speedy (a few ms).

**Comment by mistval** [comment]
Since I updated to canvas 2.6.0, `npm install` shouldn't give you these difficulties anymore. If you get a chance please try it. If everything installs easily, I'll consider this issue resolved.

**Comment by mistval** [comment]
Kotoba now installs without any node-gyp step required on most systems (pre-built binaries are downloaded for the native packages).
