### ISSUE TITLE
Potential need to refactor in jisho_search

### ISSUE THREAD

**Issue by Alkhwarizm** [mistval/kotoba#115]
When working on #114, I noticed something in jisho_search.js, in [here](https://github.com/mistval/kotoba/blob/14f1c6ab43042d544effbe2ff55cecc50b1ee476/bot/src/discord/jisho_search.js#L46) and [here](https://github.com/mistval/kotoba/blob/14f1c6ab43042d544effbe2ff55cecc50b1ee476/bot/src/discord/jisho_search.js#L57).

The `pageCount` is accessed by its length property, while it should be a number. I also noticed that `hasMultiplePages` property of `NavigationChapterInformation` is never accessed, making the `pageCount` unnecessary.
Or am I missing something?

**Comment by mistval** [comment]
Nice catch, this is dead code, so I just removed it in f63281c5c0a9
