### ISSUE TITLE
Add a 教科書体 font

### ISSUE THREAD

**Issue by TianyiShi2001** [mistval/kotoba#147]
Currently none of the fonts available for selection is a 教科書体. I think it would be helpful to have one, since 教科書体 is used in schools as a standard to which students are expected to imitate, and thus having a 教科書体 in kotoba helps learners to write better kana and kanji.

**Comment by mistval** [comment]
Hi, we have actually looked for 教科書体 fonts before, but we didn't find any good ones that would be free to use in Kotoba. Do you know any?

**Comment by mistval** [comment]
Feel free to re-open if you do know any. Also the `Eishiikaisho` font in Kotoba should be pretty close to 教科書体 so try that out if you haven't already.
