### ISSUE TITLE
Bot doesn't work in threads.

### ISSUE THREAD

**Issue by TheChilliPL** [mistval/kotoba#197]
The bot doesn't work at all when trying to start the quiz in a thread.

![image](https://user-images.githubusercontent.com/18823939/137587943-029ac4e2-0154-4181-b930-25d724c61b66.png)

**Comment by midse** [comment]
Hello,
Thread support is available in Eris since 0.16.0 https://github.com/abalabahaha/eris/releases/tag/0.16.0
Do you need some help with the implementation?

**Comment by mistval** [comment]
Hello, this is on my radar, I've just been busy. I should be able to update to 0.16.0 soon, maybe today.

**Comment by mistval** [comment]
Kotoba has been updated to eris@0.16.1 and all features should now work in threads.
