### ISSUE TITLE
N1 Grammar Quiz Nitpick: お気にめした vs お気にいたした

### ISSUE THREAD

**Issue by soamsy** [mistval/kotoba#203]
Was playing with grammar quiz recently, and I noticed this question has the wrong answer:

お気に（　　　）のなら、さしあげます。
Possible Answers
1: あがった
2: めした
3: いたした
4: なられた

Correct answer should be 2, but the quiz tells me it's 3.

Reasoning: when I google "お気に致した", "お気にいたした", etc. with double quotes specifically, the only 5 or so results that come back which are hinative questions where natives explain how お気に召した is the correct one e.g.

https://hinative.com/questions/19940883
https://hinative.com/ja/questions/13527309 (person posing the question also asserts it's 3, so I assume they're looking at the same quiz data as kotoba)

Not sure if this is something that can be changed since I'm not sure where the quiz data comes from (not in the repo due to copyright concerns I assume).

**Comment by mistval** [comment]
Thanks, I will update this question 👍
