### ISSUE TITLE
`glob` is not installed in `node-common`

### ISSUE THREAD

**Issue by Riolku** [mistval/kotoba#211]
I'm trying a fresh build, and I think this causes mysterious errors unless you have `glob` globally installed.

**Comment by mistval** [comment]
Hi, can you try running `npm install` in `./node-common` and then try building the other projects again?

**Comment by Riolku** [comment]
I couldve sworn I tried this, but Ill try that in a bit.

**Comment by Riolku** [comment]
I think the confusion arose from the fact that although `buildresources` runs in `api`, it requires `node-common` to have been properly installed. Seems to work now, sorry.

**Comment by mistval** [comment]
The README was also missing that bit about installing `node-common` so I just updated it with that. I think that step only became necessary with NPM 7 or maybe 6.
