### ISSUE TITLE
Shiritori Lax settings can be set per-user

### ISSUE THREAD

**Issue by Riolku** [mistval/kotoba#215]
Basically, for Shiritori settings, if a user tries to set it and does not have admin perms or the like, they are told the setting is set for them. However, I'm pretty sure that's nonsense, and if it isn't, it should be. I don't understand enough about Monochrome to figure out how to fix it though.

**Comment by mistval** [comment]
I think that's good for normal shiritori, but for shiritori forever it shouldn't be a user setting. It's easy to fix, we can just add `userSetting: false` to the setting in bot_settings.js.

**Comment by Riolku** [comment]
WDYM by it's good for normal shiritori? That's expected behaviour? Doesn't that mean that users will play with different settings during a game? Or do the settings for the game depend on who starts it?

**Comment by mistval** [comment]
Normal shiritori gets the settings only when the command to start the game is executed. So it will use the settings of whoever used the command and started the game.

**Comment by Riolku** [comment]
But since Shiritori Forever is a per-channel admin command type thing, it should not be a userSetting.

**Comment by Riolku** [comment]
Looks like it's already not a user setting in shiritori forever. Should be good, thanks.
