### ISSUE TITLE
Throwing an Error when there are no words, and Small Letters with no Followup

### ISSUE THREAD

**Issue by Riolku** [mistval/kotoba#217]
When there are no words available to play in Shiritori, the bot simply says it errors (presumably, it did). 

This used to be a non-issue, but with the event of #214, パーティ has no followup words. We could split small letters into two categories: those where followup words are possible and those where they aren't, but then what would the expected behaviour be? I feel like if small letters are off, パーティ would list て as the only possible starting letter, but maybe that opinion isn't shared.

**Comment by Riolku** [comment]
I can PR a change, I'm just not fully sure what we should do. I feel like one way or another, it'd be nice if パーティ and variants didn't immediately stop the game.

**Comment by mistval** [comment]
Maybe we can allow `ち` to follow `てぃ`.

**Comment by mistval** [comment]
Or `て`, I think that's fine too.
