### ISSUE TITLE
Website kanji game quiz should let you type in romaji

### ISSUE THREAD

**Issue by nico-abram** [mistval/kotoba#230]
Not sure if intentional, but when I tried N5 and kanken 10 on the website's kanji game, I couldn't get it to work with latin letters. The hiragana quiz seems to work with them. I was surprised since the bot worked fine.

Thanks for the bot/website! It's really good

**Comment by mistval** [comment]
Hi, the website has more limited features than the bot, including this difference. I don't work on the website much since it has less users, but feel free to add this as an idea in [Discussions](https://github.com/mistval/kotoba/discussions/categories/ideas) if it's important to you.
