### ISSUE TITLE
意織 instead of 意識

### ISSUE THREAD

**Issue by nayfaan** [mistval/kotoba#241]
in k!quiz N3, the prompt shown for 意識 is shown as 意織 (at least in the font I use, see attached file). Not sure if this is my font not being able to show 識 or if it's an error in the database.
![upload](https://user-images.githubusercontent.com/10527873/194681050-0b5ada63-4955-42db-811a-cb7fcb9f3fec.png)

**Comment by nayfaan** [comment]
font in use here: 
13. Genkai Mincho - An apocalyptic font

**Comment by mistval** [comment]
Hi, it's the font, it's correct in the data and the other fonts. Not something I can fix, sorry.
