### ISSUE TITLE
Conquest max missed question ignored

### ISSUE THREAD

**Issue by yant0** [mistval/kotoba#269]
https://user-images.githubusercontent.com/80298071/216757619-6712b138-4647-4295-8e99-e51c2ca5733a.mp4

I dont think this was the case just december last year? I turned the mmq=0 both at the settings and when i was about to start quiz.

**Comment by mistval** [comment]
Hi, `0` means infinite. If you want it to fail after 1 missed question, try setting it to `1`.

**Comment by yant0** [comment]
Sorry for the late response. I was actually trying to not restart the conquest quiz but even after setting it to 0 it still fails me after a few tries.

**Comment by mistval** [comment]
You mean you want to change the setting for a saved quiz? You can load it like `k!quiz load 1 mmq=0`.

**Comment by yant0** [comment]
I forgot of what the contents of the video are but i think i tried
- changing mmq=0 in settings
- typing mmq=0 with k!q
- typing mmq=0 with k!q load
I dont know now if the problem persist because i recoded the video on december, and because of that, i haven't used the bot since. I might try with mmq=999 if i feel intrested on using the bot again. Thank you for your time
