### ISSUE TITLE
Can't enable a command for a forum channel

### ISSUE THREAD

**Issue by jacobalbano** [mistval/kotoba#280]
**Enabling a command for a forum _channel_ should apply the setting to _threads_ in the forum**

On our server we have the `k!quiz` command disabled server-wide, and only turned on in a few channels. I wanted it to be made available to all threads in a forum channel, but I have to enable it per-thread.

Considering that it's impossible to type in a forum channel directly (without a thread), intuitively I would expect that enabling a command for a forum would also enable it for all threads automatically; if I'm off base here or there's another way to handle this, I wasn't able to find it.

**To Reproduce**

- Join a forum thread and enter the following commands:
  - k!settings
  - 2 (enabled commands)
  - 16 (quiz)
- Assuming the server default is "disabled", you should see "current status: disabled"
- Enter the following commands:
  - Enabled
  - <#forum_channel_id> (should auto-complete to create a link)
- The bot should now say "the new setting has been applied to channels: " and repeat the name of the channel that was entered
- k!quiz will still not work in the current thread
- Enter the following commands:
  - k!settings
  - 2
  - 16
- The result will still say "current status: disabled"
- Enter the following commands:
  - Enabled
  - This channel
- The bot should now say "the new setting has been applied to this channel"
- k!quiz will now work in the thread, but not in other threads in the same forum

**Comment by mistval** [comment]
Hi, actually I was working on something similar over the weekend, making threads inherit settings from their parent channel: https://github.com/mistval/monochrome/commit/2f979b972f2e094d765d293ed7f61c67011becd2

Didn't think about forum channels but I'll see if I can make that work for them too.

**Comment by mistval** [comment]
This should work now, feel free to reopen if you encounter any problems.
