### ISSUE TITLE
handling failed reviews

### ISSUE THREAD

**Issue by nlguillemot** [mistval/kotoba#29]
Just a suggestion. Here's my user story:

* Suppose you just did a quiz and failed 10 questions, so you begin a review quiz to correct yourself.
* However, it turns out that you couldn't remember the first 5 review questions, so you fail the review quiz itself.
* If you ask for another review, you'll get back a shorter review quiz, consisting of only the 5 first questions that you missed. The later 5 questions of the original review quiz are just gone forever.

I would like to avoid losing review questions like this due to failing review quizzes.

Some suggested workarounds:

* Disable the concept of failing a review quiz. (Problem: Quiz might go on for a long time by itself if the user leaves.)
* Make it so a review quiz review includes the whole list of not-yet-answered review questions, rather than only the ones that were failed in the last review pass.

**Comment by mistval** [comment]
Thanks for the suggestion. I think your second option would be an all-around improvement so I'll plan on implementing that.

In the meantime, I'm not sure if it's suitable for your specific circumstances, but a server admin can increase the unanswered question limit in **k!settings quiz/japanese/unanswered_question_limit**

**Comment by mistval** [comment]
Implemented and deployed: https://github.com/mistval/kotoba/commit/7efaf7ca369b3790881f0d531efa813ad36ba954

Now when a review quiz ends, the "unanswered questions" also contains the questions that were not even seen. Starting a new review quiz will contain those questions.
