### ISSUE TITLE
Conjugate command

### ISSUE THREAD

**Issue by mistval** [mistval/kotoba#64]
User suggestion

"
then, can you add a command that shows all the conjugations for verbs and nouns?
Such as miru can be mitai
Or mitte
...
Because there’s currently only a deconjugate
And that’s in alpha
But I think conjugating is more important as for me than to deconjugate
Since I’m learning a foreign language (Japanese)
"

**Comment by InnerReailty** [comment]
I was about to suggest that. It would be helpful if kotoba can show conjugations for the verb!
Btw, your bot is really helpful while discussing japanese on discord.

**Comment by mistval** [comment]
Thanks. I would like to add this sometime, but currently I am more focused on refining existing features and improving scalability.
