### ISSUE TITLE
User suggestion: Support for RGBA

### ISSUE THREAD

**Issue by mjuzikfrik** [mistval/kotoba#82]
It'd be nice to be able to set the background colour for quizes to be transparent so that it blends with the rest of the theme be it a default one or a custom one.

**Comment by mistval** [comment]
Hi, that should work already, try entering **rgba(0,0,0,0)** for a transparent background color :)

**Comment by mjuzikfrik** [comment]
It indeed does work. I used a different colour than black and it gave me an error. 
Thank you! :)
