### ISSUE TITLE
Try using JMDict for shiritori

### ISSUE THREAD

**Issue by mistval** [mistval/kotoba#99]
It might have better ordering.

**Comment by dcsan** [comment]
what ordering do you mean? difficulty?
theres also tatoeba.org that has a lot of sentences.

**Comment by mistval** [comment]
Ordering of readings for kanji. For example the first reading in EDICT2 for 机 is つき. So if you say 机 during shiritori, the bot will use つき as the reading. But it would be better if it used つくえ as that is the (much) more common reading. According to Kaito the ordering at least for this word, and hopefully others too, is better in JMDict.

**Comment by mistval** [comment]
Other improvements for shiritori:
1. Allow inputting both kanji and hiragana, to disambiguate which word you want.
2. Add settings to shiritori forever to allow you to specify:
  a. Within how many hours the same reading is not allowed to be used.
  b. Within how many turns the same reading is not allowed to be used.
  c. Whether or not a user is allowed to take consecutive turns.

**Comment by mistval** [comment]
Finally got around to this, it does seem a bit better with JMDict.
